### PR TITLE
Add Teamagochi Project

### PR DESCRIPTION
**Pull request by AnnsAnns**
Teamagochi was a student project of this years HAW Riot Course, all code is completely open source including the PCB.

### CODE REVIEW

**Review by Teufelchen1 — APPROVED** [review]
I think we can add it for now. Bachelor projects tend to die soon after they are finished - we might want to revisit this entry in a year.

But this years project was indeed very cool, although buggy ;)

**Comment by chrysn** [comment]
On Mon, Sep 16, 2024 at 01:49:41AM -0700, Teufelchen wrote:
> I think we can add it for now. Bachelor projects tend to die soon after they are finished - we might want to revisit this entry in a year.

Might it make sense to split the section into "mainained" and
"completed" projects, then?

**Comment by AnnsAnns** [comment]
While that would be cool, adding a section that is actively called "maintained" might make it harder to maintain the list and give the wrong impression to users when they click on projects under the maintained list that aren't actively maintained anymore.

**Comment by AnnsAnns** [comment]
> But this years project was indeed very cool, although buggy ;)

Hey, in the end everything worked out :sweat_smile: : At least the RIOT part of the project didn't require any fixes for the final presentation as it worked fine under the constraints we set ourselves (Offline behavior -> undefined)

I'll however try to check whether the last minute bug fixes have been properly merged so any user that would be willingly to set up the entire project would be able to properly use it without any major issues.

**Comment by kaspar030** [comment]
> Might it make sense to split the section into "mainained" and "completed" projects, then?

IMO "maintained" should be the implicit default. does "completed" mean the right thing? maybe "historical" fits better?

**Comment by Teufelchen1** [comment]
Hm I feel "completed" is a good choice. Sometimes you just want to build something and then...it's done.
While "historical" feels a bit like "yeah this is project from before we had a big change in RIOT". 

But in the end, both wordings are fine. If we do go down that path, we also need to move the MiniLoon project there.

**Comment by MrKevinWeiss** [comment]
I think it looks OK.

**Pull request merged**
